# 権限の設定
sudo: required
# dockerを使う
services: docker
# コンテナを起動
before_install:
　- docker login -u 19770303 -p f6fe56bf-f914-4038-b0f0-49bbe48977b0
  - docker-compose up -build -d
# DB準備
script:
  docker-compose exec --env 'RAILS_ENV=test' web rails db.create
  docker-compose exec --env 'RAILS_ENV=test' web rails db.migrate
 # テスト実行
  docker-compose exec --env 'RAILS_ENV=test' web rails test
